### PR TITLE
Loop over carousel

### PR DESCRIPTION
**Pull request by joselcvarela**

### CODE REVIEW

**Comment by Ashokkumar1995** [comment]
if i dont want this, what i have to do to get normal loop

**Comment by jac0117** [comment]
can you cut a new release with this change?

**Comment by d10k6** [comment]
Did a new release with this feature get published?

**Comment by jac0117** [comment]
No. This project is no longer maintained. 

Try ngx carousel. 100 times better. 
https://sheikalthaf.github.io/ngx-carousel/

**Pull request closed without merging**
